### ISSUE TITLE
Docker compose file?

### ISSUE THREAD

**Issue by 19wolf** [abeloin/Jackett#6]
Until this fork is pulled; is there a docker-compose file available in this repo? Can I just replace `image: linuxserver/jackett` with ... what image exactly? There was confusing information in the thread on the main repo.

**Comment by abeloin** [comment]
Taken from this comment: https://github.com/Jackett/Jackett/issues/9029#issuecomment-731564174 

This should do the trick, you may have to edit it for the run options

```
version: "2.1"
services:
  jackett:
#   image: linuxserver/jackett
    image: sclemenceau/docker-jackett:cloudproxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - RUN_OPTS= # run options here optional
    volumes:
      - ./jackett/conf:/config
      - ./jackett/blackhole:/downloads
    # ports:
    #   - 9117:9117
    restart: unless-stopped
    networks:
      - torrent
  flaresolver:
    image: noahcardoza/cloudproxy
    restart: unless-stopped
    networks:
      - torrent
networks:
    torrent:
      external: false
```

In jacket setting:

CloudProxy API Url: http://flaresolver:8191/
